### ISSUE TITLE
Pass custom items to `ignoredFiles` array

### ISSUE THREAD

**Issue by joshgillies** [zeit/list#26]
I've noticed that currently `ignoredFiles` is a hard coded array, and wonder whether there's much value to offering a method to customise the items in this list? The addition of an `--ignore` flag would suffice.

**Comment by joshgillies** [comment]
An interesting idea just crossed my mind, what if `list` parsed `.gitignore` or `.npmignore` to base it's ignored files/folder off.

**Comment by leo** [comment]
Fixed in https://github.com/zeit/list/pull/44
