### ISSUE TITLE
Basic password protection

### ISSUE THREAD

**Issue by guidobouman** [zeit/list#30]
When using list, you might want to supply a password to protect your directory or static site.

This is especially important when using [now-serve](https://github.com/zeit/now-serve) to serve a staging environment that should not be reachable by every person on the internet.

**Comment by guidobouman** [comment]
@leo I'm working on a PR, should this be in the form of a [micro](https://github.com/zeit/micro)-plugin or can I use [http-auth](https://www.npmjs.com/package/http-auth)?

**Comment by rauchg** [comment]
This is a cool idea. Maybe with envs? `HTTP_BASIC_USER` and `HTTP_BASIC_PASSWORD` ?

**Comment by guidobouman** [comment]
Yeah, I thought the same. Or with a `HTTP_BASIC_AUTH` string: `username:password` or `username:password_hash`

**Comment by taravancil** [comment]
@guidobouman are you still working on this? I was thinking about taking a stab at it, but I don't want to jump in if you're still planning to do it 😄

**Comment by guidobouman** [comment]
Have a go! I can assist if you're running into any issues.

**Comment by taravancil** [comment]
Cool, thanks!

**Comment by timkendall** [comment]
Implemented this as just more CLI flags. Let me know what you guys think.

**Comment by leo** [comment]
https://github.com/zeit/list/pull/49

**Comment by paulintrognon** [comment]
Hi, since the rewrite I can't see this option anywhere. Is it still possible to add a basic protection?

**Comment by flawyte** [comment]
@paulintrognon Yes, but it seems like the only way now is to do it by yourself. See how [here](https://github.com/flawyte/now-basic-auth).
