### ISSUE TITLE
Allow to pass custom path to list

### ISSUE THREAD

**Issue by slorber** [zeit/list#38]
I published my own list with cors support for testing, until it's merged/released

I did use it like that:

```
12:17 $ ns build -c 'list --cors' -p list-seb
> Deploying /private/var/folders/qm/y2hrgmys1q317t0nfk53mzqm0000gp/T/now-serve-419dd99ce51585c88ee6ec1e97c55117
> Using Node.js 6.9.0 (default)
> Ready! https://ns-edvokxmqio.now.sh (copied to clipboard) [5s]
> Upload [====================] 100% 0.0s
> Sync complete (138B) [3s]
> Initializing…
> Building
> ▲ npm install
> Installing package list-seb@latest
> ▲ npm start
> Deployment complete!
```

The problem is that this deployment does not show my files directly, but it shows /node_modules, /content and package.json.

now-server is clever and knows that it has to serve the /content folder instead of the root. It's like to be able to mimic this behavior when using ns with the --command option, so that I can use my own fork in the same way:

```
ns build -c 'list --cors --path "/content"' -p list-seb 
```

**Comment by leo** [comment]
`list ./content`

**Comment by slorber** [comment]
Obviously it's only when you open an issue that you finally see the solution :)
