### ISSUE TITLE
Dir vs regular file detection

### ISSUE THREAD

**Issue by OlliV** [zeit/list#42]
It seems `list` assumes a file is a directory if it doesn't have an extension.

https://xyz-ratcfalrqb.now.sh/

In this case `file` is a regular file containing text `HELLO`. The proper way of checking the file type is to use one of the stat functions: https://nodejs.org/api/fs.html#fs_fs_stat_path_callback

**Comment by taravancil** [comment]
I just [submitted a PR](https://github.com/zeit/list/pull/43) to fix this 😃

**Comment by leo** [comment]
https://github.com/zeit/list/pull/43
